// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFsZXh04up_ICEyhRxmtIgSU5nH_rkgKk',
    appId: '1:834599326154:web:0f06dfb0bc005ad43cff33',
    messagingSenderId: '834599326154',
    projectId: 'drive-5e3cd',
    authDomain: 'drive-5e3cd.firebaseapp.com',
    databaseURL: 'https://drive-5e3cd-default-rtdb.firebaseio.com',
    storageBucket: 'drive-5e3cd.firebasestorage.app',
    measurementId: 'G-2H023PVNJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz-Gi8aeFAVsW3uidlETtbNLWonGTj12Q',
    appId: '1:834599326154:android:09bd01a84c4a43863cff33',
    messagingSenderId: '834599326154',
    projectId: 'drive-5e3cd',
    databaseURL: 'https://drive-5e3cd-default-rtdb.firebaseio.com',
    storageBucket: 'drive-5e3cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAakp2WvfNQhBugRraEh2Zy5xIz2YylMb4',
    appId: '1:834599326154:ios:171ef37cfbde987b3cff33',
    messagingSenderId: '834599326154',
    projectId: 'drive-5e3cd',
    databaseURL: 'https://drive-5e3cd-default-rtdb.firebaseio.com',
    storageBucket: 'drive-5e3cd.firebasestorage.app',
    iosBundleId: 'com.example.projet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAakp2WvfNQhBugRraEh2Zy5xIz2YylMb4',
    appId: '1:834599326154:ios:171ef37cfbde987b3cff33',
    messagingSenderId: '834599326154',
    projectId: 'drive-5e3cd',
    databaseURL: 'https://drive-5e3cd-default-rtdb.firebaseio.com',
    storageBucket: 'drive-5e3cd.firebasestorage.app',
    iosBundleId: 'com.example.projet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFsZXh04up_ICEyhRxmtIgSU5nH_rkgKk',
    appId: '1:834599326154:web:3f64778155c615713cff33',
    messagingSenderId: '834599326154',
    projectId: 'drive-5e3cd',
    authDomain: 'drive-5e3cd.firebaseapp.com',
    databaseURL: 'https://drive-5e3cd-default-rtdb.firebaseio.com',
    storageBucket: 'drive-5e3cd.firebasestorage.app',
    measurementId: 'G-MJC85SZ4D5',
  );
}
